language: python

matrix:
  include:
    - python: 3.6
    - python: 3.7
    - python: 3.8
    - python: pypy3

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - pytest .
  - pytest --cov=urdu_characters
  - codecov

notifications:
  slack: urduhack:HarNbK5WrXQbu9XuFLPsSFtM